### ISSUE TITLE
Tests fails with default configuration

### ISSUE THREAD

**Issue by orweinberger** [joola/joola#730]
Fresh clone of joola, npm install, npm test:

```
shraga@ws-01:~/joola/joola$ npm test

> joola@0.8.14 pretest /home/shraga/joola/joola
> npm run lint


> joola@0.8.14 lint /home/shraga/joola/joola
> jshint --exclude ./lib/webserver/public ./lib ./test


> joola@0.8.14 test /home/shraga/joola/joola
> JOOLA_CONFIG_STORE_LOGGER_CONSOLE_LEVEL=trace NODE_CONFIG_DIR=$(pwd)/test/config mocha test/ --reporter spec



07:37:59.514Z  INFO joola: Found geoip-lite module.
07:37:59.620Z  INFO joola: Found a valid configuration store with version [0.1.60].
07:37:59.622Z DEBUG joola: Setting environment varialbe for configuration [store.logger.console.level]: trace
07:37:59.622Z DEBUG joola: Setting environment varialbe for configuration [interfaces.webserver.secureonly]: false
07:37:59.622Z DEBUG joola: Setting environment varialbe for configuration [authentication.basicauth.enabled]: true
07:37:59.624Z DEBUG joola: File logging disabled. Could not resolve path to log file [/var/log/joola/log-31221.log]: Path missing
07:37:59.674Z DEBUG joola: State for [dispatch] changed to [working]: dispatch is up.
07:37:59.675Z TRACE joola: [dispatch] listen on: config:change
07:37:59.676Z DEBUG joola: Message dispatch online.
  1) "before all" hook
  2) "after all" hook

  0 passing (805ms)
  2 failing

  1)  "before all" hook:
     Uncaught TypeError: Object.keys called on non-object
      at Function.keys (native)
      at Object.datastore.init (lib/common/datastore.js:30:10)
      at lib/joola.js:104:23
      at lib/dispatch/index.js:261:16

  2)  "after all" hook:
     ReferenceError: engine is not defined
      at Context.<anonymous> (test/unit/runner.js:55:7)



npm ERR! Test failed.  See above for more details
```

**Comment by itayw** [comment]
Tests can be a bit tricky.

The easiest way to get tests running is by using `$ npm run test:scenario` or specifically `$ npm run test:scenario:elasticsearch`.
